Show article
CraftAcademy/paps pull request #13
Opened 2018-03-17 16:17 UTC by AntonellaMorittu

#### PT Story: https://www.pivotaltracker.com/story/show/155970273
#### Description
Changes proposed in this pull request:

* Add show article(s) page

#### What I have learned working on this feature: 
To stay within scope!

#### Screenshots:
![schermata 2018-03-15 alle 17 46 40](https://user-images.githubusercontent.com/33493978/37516728-64899abe-290f-11e8-9255-5b8a29cb2def.png)

2018-03-17 16:19 UTC, isabellelii approved these changes

2018-03-17 16:24 UTC, tochman approved these changes

2018-03-17 16:39 UTC, AKidd95 requested changes

2018-03-17 16:39 UTC, AKidd95 commented on features/create_articles.feature
> -    Then I should stay on new article page
did you delete this Then line? something needs to happen after you click "create article"

2018-03-17 16:39 UTC, AKidd95 commented on features/create_articles.feature
> -    Then I should stay on new article page
same here

2018-03-18 13:21 UTC, AKidd95 approved these changes

2018-03-18 13:22 UTC, merged