Initial setup of Rails 5.2 app
CraftAcademy/paps pull request #2
Opened 2018-03-14 16:00 UTC by davidboll

#### PT Story: https://www.pivotaltracker.com/story/show/155896828
#### Description
Initial setup of Rails 5.2 app with RSpec and Cucumber
Changes proposed in this pull request:
* Adds RSpec
* Adds Cucumber
* Adds Haml
#### What I have learned working on this feature: 
How to Scaffold a Rails 5.2 app

2018-03-14 16:15 UTC, tochman reviewed
Please see comments

2018-03-14 16:15 UTC, tochman commented on Gemfile
> +gem 'coffee-rails', '~> 4.2'
I would remove this

2018-03-14 16:15 UTC, tochman commented on Gemfile
> +gem 'jbuilder', '~> 2.5'
I would remove this

2018-03-14 16:48 UTC, AKidd95 commented on Gemfile
> +gem 'jbuilder', '~> 2.5'
Thanks, will do

2018-03-14 18:12 UTC, tochman requested changes

2018-03-14 18:12 UTC, tochman commented on coverage/.last_run.json
> +}
Please remove coverage files

2018-03-14 18:15 UTC, davidboll commented on coverage/.last_run.json
> +}
Your wish is my command :)

2018-03-15 07:42 UTC, tochman approved these changes

2018-03-15 07:43 UTC, tochman commented
Looks good to me now. I would translate the application layout templates to HAML but that can be done in another PR. This one is ready to merge IMO

2018-03-15 07:49 UTC, merged